### ISSUE TITLE
sudo is missing in the dockers .....

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud-docker/enterprise#2]
usually when we try to execute occ as root the suggestion is to run it with sudo

![bildschirmfoto von 2017-08-23 11-43-27](https://user-images.githubusercontent.com/1005065/29609717-5142e90a-87f8-11e7-9658-ed93602cf23d.png)

**Comment by pmaier1** [comment]
@tboerger Please take care.

**Comment by tboerger** [comment]
No sudo within docker containers, you are already root.

**Comment by pmaier1** [comment]
Anyway you don't need to execute occ as webserver user anymore, right? Yesterday I did an 'occ upgrade' within docker and that went flawlessly.

**Comment by DeepDiver1975** [comment]
> No sudo within docker containers, you are already root.

its not about getting root but switch the user to www-data.
while there are multiple ways of switching the user our suggestion in occ is to use sudo.

from an ux pov its bad to suggest sudo and not provide sudo ...

**Comment by tboerger** [comment]
Somebody forgot to add the info about the occ wrapper to this readme: https://github.com/owncloud-docker/server/blob/master/README.md#commandline-commands

**Comment by DeepDiver1975** [comment]
> Anyway you don't need to execute occ as webserver user anymore, right?

you need to - e.g. when touching files it is necessary to do this as www-data

**Comment by tboerger** [comment]
You don't need sudo for that, just execute occ from the path (without ./ in front of it)
