### ISSUE TITLE
10.2 tag is not there, Tags page leads to a 404

### ISSUE THREAD

**Issue by voroyam** [owncloud-docker/enterprise#20]
https://hub.docker.com/r/owncloud/enterprise/tags/

leads to a 404

----

other errors:

docker-compose up -d
Creating network "compose_default" with the default driver
Pulling owncloud (owncloud/enterprise:10.2)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]n
ERROR: pull access denied for owncloud/enterprise, repository does not exist or may require 'docker login'

-------

ull registry.owncloud.com/owncloud/enterprise:10.2.0
Error response from daemon: Get https://registry.owncloud.com/v2/owncloud/enterprise/manifests/10.2.0: received unexpected HTTP status: 500 Internal Server Error

**Comment by tboerger** [comment]
The badge got to be removed
